app_version: 24.7
capabilities:
- description: NZBGet is able to chown files.
  name: CHOWN
- description: NZBGet is able bypass permission checks for it's sub-processes.
  name: FOWNER
- description: NZBGet is able to set group ID for it's sub-processes.
  name: SETGID
- description: NZBGet is able to set user ID for it's sub-processes.
  name: SETUID
categories:
- media
description: NZBGet is a binary downloader, which downloads files from Usenet based-on
  information given in nzb files.
home: https://nzbget.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/nzbget/icons/icon.svg
keywords:
- media
- usenet
- newsreader
lib_version: 2.1.17
lib_version_hash: fac0bd3f679320fc7366687de39b822c1c53241b4aa0cb85080d6d6843322154
maintainers:
- email: nzbget@nzbget.com
  name: nzbget
  url: https://nzbget.com/
name: nzbget
run_as_context:
- description: NZBGet runs as any non-root user.
  gid: 568
  group_name: nzbget
  uid: 568
  user_name: nzbget
screenshots:
- https://media.sys.truenas.net/apps/nzbget/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/nzbget/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/nzbget/screenshots/screenshot3.png
sources:
- https://github.com/nzbgetcom/nzbget
title: NZBGet
train: community
version: 1.0.1
